{"text":"@startuml\nactor User\nparticipant \"Telegram App\" as App\nparticipant \"Telegram Bot API\" as API\nparticipant \"Bot Backend\" as Backend\ndatabase \"Database\" as DB\nparticipant \"External Service\" as Service\n\nUser -> App: Enviar mensaje\nApp -> API: Enviar mensaje\nAPI -> Backend: Enviar mensaje (Webhook)\nBackend -> DB: (Opcional) Consultar\/Guardar datos de usuario\nBackend -> Service: (Opcional) Consultar API externa\nService --> Backend: Respuesta de API externa\nBackend -> API: Enviar respuesta\nAPI -> App: Reenviar respuesta\nApp -> User: Mostrar respuesta\n\n@enduml\n","drawing":"d3Jk8AEACAA6DggAEP\/\/\/\/\/\/\/\/\/\/fxgAQhDN\/FwXKHhNJKwkGBa6XNzX"}